#!/bin/sh
docker run \
-e TZ=America/Denver \
-e GQLAPI_CRYPT_KEY='gt6mLqxBdzb75W5gen66X9DKwT9fajHtsC1cbdERTS0=' \
-p $1:8443 \
-v $PWD/grapinator/resources:/opt/grapinator/grapinator/resources \
-v $PWD/grapinator/resources.$2/grapinator.ini.docker:/opt/grapinator/grapinator/resources/grapinator.ini \
-v $PWD/grapinator/resources.$2/schema.dct:/opt/grapinator/grapinator/resources/schema.dct \
-v $PWD/grapinator/resources:/certs \
--name grapinator_$2 grapinator:latest 
